name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Install Dependencies
        run: |
          cd backend && npm install
          cd ../frontend && npm install
          
      - name: Set execute permissions for Jest
        run: chmod +x backend/node_modules/.bin/jest
      
      - name: Run Tests
        run: |
          cd backend && npm test
          cd ../frontend && npm test

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensures that the deploy job runs after the build job
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up AWS CLI
        run: |
          aws configure set region ap-southeast-1
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deploy to AWS
        run: |
          aws ecs update-service --cluster bingo-cluster --service backend --force-new-deployment --region ap-southeast-1
